export const milestonesData = [
    {
        parentJob: 'SAE23072017',
        milestoneDesc: 'Pickup Cartage Complete/Finalized',
        milestoneDate: '',
        milestoneStatus: '',
    },
    {
        parentJob: 'SAE23072017',
        milestoneDesc: 'Origin Receival from Wharf/Depot',
        milestoneDate: '',
        milestoneStatus: '',
    },
    {
        parentJob: 'SAE23072017',
        milestoneDesc: 'All Export Documents Received',
        milestoneDate: '',
        milestoneStatus: '',
    },
    {
        parentJob: 'C000001327',
        milestoneDesc: 'Departure from First Load Port',
        milestoneDate: '11-Jul-2023',
        milestoneStatus: 'overdue',
    },
    {
        parentJob: ['C000001327'],
        milestoneDesc: ['Arrival at Final Discharge Port'],
        milestoneDate: '22-Jul-2023',
        milestoneStatus: 'overdue',
    },
]

export const goodsData = [
    {
        goodsPiece: '47',
        goodsPackType: 'Drum',
        goodsLength: '0.000',
        goodsWidth: '0.000',
        goodsHeight: '0.000',
        goodsHeightUD: 'M',
        goodsWeight: '1,217.300',
        goodsWeightUQ: 'KG',
        goodsVolume: '11.031',
        goodsVolumeUQ: 'M3',
        goodsDescription: 'MARUKA LYNCUR CS3',
        goodsMarksAndNumbers: '',
        goodsLinePrice: '0.00',
        goodsCurrency: 'JPY',
        goodsTariffNum: '',
        goodsContainer: '',
    },
    {
        goodsPiece: '47',
        goodsPackType: 'Drum',
        goodsLength: '0.000',
        goodsWidth: '0.000',
        goodsHeight: '0.000',
        goodsHeightUD: 'M',
        goodsWeight: '1,217.300',
        goodsWeightUQ: 'KG',
        goodsVolume: '11.031',
        goodsVolumeUQ: 'M3',
        goodsDescription: 'MARUKA LYNCUR CS3',
        goodsMarksAndNumbers: '',
        goodsLinePrice: '0.00',
        goodsCurrency: 'JPY',
        goodsTariffNum: '',
        goodsContainer: '',
    },
]

export const referenceNoData = [
    {
        refCountry: '',
        refNumbertype: '',
        refNumber: '',
        refTypeDescription: '',
    },
]

export const relatedInvoiceData = [
    {
        invoiceNo: 'INV001',
        issuer: 'Issuer 1',
        type: 'Type A',
        terms: 'Net 30',
        invDate: '2023-01-05',
        dueDate: '2023-02-04',
        currency: 'USD',
        amount: '1500',
        outstandingAmount: '750',
        paidDate: '2023-01-20',
    },
    {
        invoiceNo: 'INV002',
        issuer: 'Issuer 2',
        type: 'Type B',
        terms: 'Net 45',
        invDate: '2023-02-10',
        dueDate: '2023-03-12',
        currency: 'EUR',
        amount: '2000',
        outstandingAmount: '1000',
        paidDate: '2023-02-25',
    },
    {
        invoiceNo: 'INV003',
        issuer: 'Issuer 3',
        type: 'Type C',
        terms: 'Net 60',
        invDate: '2023-03-15',
        dueDate: '2023-04-14',
        currency: 'GBP',
        amount: '3000',
        outstandingAmount: '1500',
        paidDate: '2023-03-30',
    },
    {
        invoiceNo: 'INV004',
        issuer: 'Issuer 4',
        type: 'Type D',
        terms: 'Net 60',
        invDate: '2023-03-15',
        dueDate: '2023-04-14',
        currency: 'GBP',
        amount: '3000',
        outstandingAmount: '1500',
        paidDate: '2023-03-30',
    },
    {
        invoiceNo: 'INV005',
        issuer: 'Issuer 5',
        type: 'Type E',
        terms: 'Net 60',
        invDate: '2023-03-15',
        dueDate: '2023-04-14',
        currency: 'GBP',
        amount: '3000',
        outstandingAmount: '1500',
        paidDate: '2023-03-30',
    },
    {
        invoiceNo: 'INV006',
        issuer: 'Issuer 6',
        type: 'Type F',
        terms: 'Net 60',
        invDate: '2023-03-15',
        dueDate: '2023-04-14',
        currency: 'GBP',
        amount: '3000',
        outstandingAmount: '1500',
        paidDate: '2023-03-30',
    },
]

export const documentData = [
    {
        date: '2023-01-01',
        description: 'Sample Description 1',
        type: 'Type A',
    },
    {
        date: '2023-02-02',
        description: 'Sample Description 2',
        type: 'Type B',
    },
    {
        date: '2023-03-03',
        description: 'Sample Description 3',
        type: 'Type C',
    },
    {
        date: '2023-04-04',
        description: 'Sample Description 4',
        type: 'Type D',
    },
    {
        date: '2023-05-05',
        description: 'Sample Description 5',
        type: 'Type E',
    },
    {
        date: '2023-06-06',
        description: 'Sample Description 6',
        type: 'Type F',
    },
]