import { IMeta } from 'common/common.interface'
import { IAdditionalInformation, IBookings } from './bookings.interface'

export const DataBookings: IBookings[] = [
    {
        statusTransaction: 'all',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003000',
        shipper: 'Kaiba Corp',
        shipperContact: 'ALVIANTO',
        shipperRef: '14G04K',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '34TRRG',
        origin: 'Tokyo',
        etd: '2023-07-11',
        destination: 'Kyoto',
        eta: '2023-07-27',
        consignee: 'Konami Enterprise CO.LTD',
        consigneeContact: 'Matrix Corp',
        packs: '5 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'all',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003001',
        shipper: 'CyberPunk Enterprise',
        shipperContact: 'ALVIANTO',
        shipperRef: '1A2B3C',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '987XYZ',
        origin: 'Florida',
        etd: '2023-12-18',
        destination: 'Texas',
        eta: '2023-12-25',
        consignee: 'Matrix Corp',
        consigneeContact: 'Matrix Corp',
        packs: '45 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'all',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003002',
        shipper: 'OneByOne Logistical PTY LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: '4D5E6F',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '123ABC',
        origin: 'Melbourne',
        etd: '2023-12-20',
        destination: 'Destination X',
        eta: '2023-12-28',
        consignee: 'OneByOne Logistical PTY LTD',
        consigneeContact: 'Matrix Corp',
        packs: '37 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'all',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003003',
        shipper: 'AKB48 Entertainment Inc',
        shipperContact: 'ALVIANTO',
        shipperRef: '7G8H9I',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '456DEF',
        origin: 'Akihabara',
        etd: '2023-12-15',
        destination: 'Jakarta',
        eta: '2023-12-20',
        consignee: 'JKT48 Entertainment Inc',
        consigneeContact: 'Matrix Corp',
        packs: '50 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'all',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003004',
        shipper: 'Mihoyo CO.LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: 'J1K2L3',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '789GHI',
        origin: 'Beijing',
        etd: '2023-12-18',
        destination: 'Jakarta',
        eta: '2023-12-25',
        consignee: 'Cognoshpere CO.LTD',
        consigneeContact: 'Matrix Corp',
        packs: '42 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atdestinationport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003005',
        shipper: 'Fortune Cookies CO.LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: 'M4N5O6',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '012JKL',
        origin: 'Jakarta',
        etd: '2023-12-20',
        destination: 'Tokyo',
        eta: '2023-12-28',
        consignee: 'Unilever PLC',
        consigneeContact: 'Matrix Corp',
        packs: '55 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atdestinationport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003006',
        shipper: 'Hindia Music',
        shipperContact: 'ALVIANTO',
        shipperRef: 'P7Q8R9',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '345MNO',
        origin: 'Jakarta',
        etd: '2023-12-15',
        destination: 'New York',
        eta: '2023-12-20',
        consignee: 'Vevo LLC',
        consigneeContact: 'Matrix Corp',
        packs: '37 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atdestinationport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'BB00003007',
        shipper: 'Sam and Ella Pizza',
        shipperContact: 'ALVIANTO',
        shipperRef: '789ABC',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: 'DEF123',
        origin: 'Milan',
        etd: '2023-12-18',
        destination: 'Florida',
        eta: '2023-12-25',
        consignee: 'Ella and Sam Food',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atdestinationport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003008',
        shipper: 'Passmore Gas & Propane',
        shipperContact: 'ALVIANTO',
        shipperRef: 'MNO123',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '456PQR',
        origin: 'Mariana',
        etd: '2023-12-20',
        destination: 'Hawaii',
        eta: '2023-12-28',
        consignee: 'Britis Petroleum',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atdestinationport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003009',
        shipper: 'Krusty Krab CO.LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: 'STU789',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: 'XYZ012',
        origin: 'Atoll',
        etd: '2023-12-15',
        destination: 'Adelaide',
        eta: '2023-12-20',
        consignee: 'BobSquare CO.LTD',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'intransit',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003010',
        shipper: 'OneByOne Logistical PTY LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: '345ABC',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: 'DEF678',
        origin: 'Melbourne',
        etd: '2023-12-18',
        destination: 'Sydney',
        eta: '2023-12-25',
        consignee: 'OneByOne Logistical PTY LTD',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'intransit',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003011',
        shipper: 'OneByOne Logistical PTY LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: 'JKL234',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '567MNO',
        origin: 'Melbourne',
        etd: '2023-12-20',
        destination: 'Sydney',
        eta: '2023-12-28',
        consignee: 'OneByOne Logistical PTY LTD',
        consigneeContact: 'Matrix Corp',
        packs: '48 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'intransit',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003012',
        shipper: 'OneByOne Logistical PTY LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: 'PQR901',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '234XYZ',
        origin: 'Singapore',
        etd: '2023-12-15',
        destination: 'Kenya',
        eta: '2023-12-20',
        consignee: 'OneByOne Logistical PTY LTD',
        consigneeContact: 'Matrix Corp',
        packs: '18 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'intransit',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003013',
        shipper: 'OneByOne Logistical PTY LTD',
        shipperContact: 'ALVIANTO',
        shipperRef: 'ABC567',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '890DEF',
        origin: 'Syndey',
        etd: '2023-12-18',
        destination: 'Adelaide',
        eta: '2023-12-25',
        consignee: 'OneByOne Logistical PTY LTD',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'intransit',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003014',
        shipper: 'Shipper O',
        shipperContact: 'ALVIANTO',
        shipperRef: 'GHI890',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '123JKL',
        origin: 'Origin X',
        etd: '2023-12-20',
        destination: 'Destination V',
        eta: '2023-12-28',
        consignee: 'Consignee 15',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atoriginport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003015',
        shipper: 'Shipper P',
        shipperContact: 'ALVIANTO',
        shipperRef: 'MNO234',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '567PQR',
        origin: 'Origin Y',
        etd: '2023-12-15',
        destination: 'Destination Z',
        eta: '2023-12-20',
        consignee: 'Consignee 16',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atoriginport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003016',
        shipper: 'Shipper Q',
        shipperContact: 'ALVIANTO',
        shipperRef: 'STU567',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '890XYZ',
        origin: 'Origin Z',
        etd: '2023-12-18',
        destination: 'Destination X',
        eta: '2023-12-25',
        consignee: 'Consignee 17',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atoriginport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003017',
        shipper: 'Shipper R',
        shipperContact: 'ALVIANTO',
        shipperRef: 'PQR345',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '678STU',
        origin: 'Origin A',
        etd: '2023-12-20',
        destination: 'Destination B',
        eta: '2023-12-28',
        consignee: 'Consignee 18',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atoriginport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003018',
        shipper: 'Shipper S',
        shipperContact: 'ALVIANTO',
        shipperRef: '901XYZ',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '234ABC',
        origin: 'Origin B',
        etd: '2023-12-15',
        destination: 'Destination C',
        eta: '2023-12-20',
        consignee: 'Consignee 19',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'atoriginport',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003019',
        shipper: 'Shipper T',
        shipperContact: 'ALVIANTO',
        shipperRef: 'DEF678',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '901GHI',
        origin: 'Origin C',
        etd: '2023-12-18',
        destination: 'Destination D',
        eta: '2023-12-25',
        consignee: 'Consignee 20',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'others',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003020',
        shipper: 'Shipper U',
        shipperContact: 'ALVIANTO',
        shipperRef: '234MNO',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '567PQR',
        origin: 'Origin D',
        etd: '2023-12-20',
        destination: 'Destination E',
        eta: '2023-12-28',
        consignee: 'Consignee 21',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'others',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003021',
        shipper: 'Shipper V',
        shipperContact: 'ALVIANTO',
        shipperRef: '890STU',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '123XYZ',
        origin: 'Origin E',
        etd: '2023-12-15',
        destination: 'Destination F',
        eta: '2023-12-20',
        consignee: 'Consignee 22',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '26PLT',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'others',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003022',
        shipper: 'Shipper W',
        shipperContact: 'ALVIANTO',
        shipperRef: '456ABC',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '789DEF',
        origin: 'Origin F',
        etd: '2023-12-18',
        destination: 'Destination G',
        eta: '2023-12-25',
        consignee: 'Consignee 23',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'others',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003023',
        shipper: 'Shipper X',
        shipperContact: 'ALVIANTO',
        shipperRef: 'JKL012',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '345GHI',
        origin: 'Origin G',
        etd: '2023-12-20',
        destination: 'Destination H',
        eta: '2023-12-28',
        consignee: 'Consignee 24',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
    {
        statusTransaction: 'others',
        transportMode: 'Air Freight (LSE)',
        bookingDate: '2023-11-02',
        bookingNo: 'B00003024',
        shipper: 'Shipper Y',
        shipperContact: 'ALVIANTO',
        shipperRef: 'STU234',
        shipperCodAmount: '45.00 Company Check',
        orderNumber: '901XYZ',
        origin: 'Origin H',
        etd: '2023-12-15',
        destination: 'Destination I',
        eta: '2023-12-20',
        consignee: 'Consignee 25',
        consigneeContact: 'Matrix Corp',
        packs: '33 PLT',
        weight: '5256.000 KG',
        volume: '34.000 M3',
        vessel: '-',
        voyageFlight: '-',
        goodsValue: '43.00 JPY',
        insuranceValue: '43.00 JPY',
        serviceLevel: 'Door to Door',
        paymentTerm: 'Collect',
        billing: '-',
        goodsDescription: 'ELECTRONIC RADIATION',
        detailedDescription: 'INFORM FOR GUIDELINES',
        notes: '-',
        specialInstructions: '-',
        marksNumber: '-',
    },
]

export const AdditionalInformationData: IAdditionalInformation[] = [
    {
        pickupAddress:
            'NIPPON SHEET GLASS CO.LTD. 255 HAMADA OBASHIMO MAIZURU CITY, OSAKA 625-B666',
        estimatedPickup: '09-Nov-2023',
        requiredPickUp: '09-Nov-2023',
        pickupEquipment: 'Premise Supplies Lift',
        pickupAgent: '-',
        deliveryAddress:
            'NIPPON SHEET GLASS CO.LTD. 255 HAMADA OBASHIMO MAIZURU CITY, OSAKA 625-B666',
        estimatedDelivery: '14-Nov-2023',
        deliveryRequiredBy: '14-Nov-2023',
        cartageDropMode: 'Premise Supplies Lift',
        deliveryAgent: '-',
        chargesApply: 'Replace all charges with "As Agreed" on both sets.',
        releaseType: 'Waiting to be Approved',
        onBoard: 'Shipped',
    },
]

export const metaDummy: IMeta = {
    current_page: 1,
    last_page: 1,
    from: 1,
    to: 25,
    total_Items: 25,
    per_page: 0,
    total_page: 0,
    index_end: 0,
    index_start: 0,
}
