import { IMeta } from 'common/common.interface'

export const UserDetailData = [
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A001',
        name: 'Amber',
        phone_number: '+62088212',
        email: 'Amber@gmail.com',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Australia',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
        address: 'Hudson Avenue',
        user_level: 'super admin',
        module_access: {
            dashboard: true,
            quotation: true,
            forwarding: true,
            liner_agency: true,
            customs: true,
            warehouse: true,
            part_transport: true,
            accounts: true,
            user: true,
        },
        log: [
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
        ],
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A002',
        phone_number: '+62088212',
        name: 'George',
        email: 'George@gmail.com',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Indonesia',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
        address: 'Hudson Avenue',
        user_level: 'super admin',
        module_access: {
            dashboard: true,
            quotation: true,
            forwarding: true,
            liner_agency: true,
            customs: true,
            warehouse: true,
            part_transport: true,
            accounts: true,
            user: true,
        },
        log: [
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
        ],
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        phone_number: '+62088212',
        email: 'june@gmail.com',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
        address: 'Hudson Avenue',
        user_level: 'super admin',
        module_access: {
            dashboard: true,
            quotation: true,
            forwarding: true,
            liner_agency: true,
            customs: false,
            warehouse: false,
            part_transport: false,
            accounts: false,
            user: true,
        },
        log: [
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
            {
                timestamp: '2023-12-09 10:30 AM',
                action: 'Update Shipment',
                description: 'Updated shipment details for order #12345',
            },
        ],
    },
]

export const SelectUAData = [
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A001',
        name: 'Amber',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Australia',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A002',
        name: 'George',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Indonesia',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'April',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'may',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'suspended',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'August',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'suspended',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'suspended',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'suspended',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'suspended',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'suspended',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'active',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
    {
        selected: false,
        image: 'img1.jpg',
        user_id: 'A003',
        name: 'june',
        role: 'Consultan Manager',
        organization_name: 'Onebyone Logistical Singapura',
        status: 'suspended',
        last_access: '02 Aug 2023 | 07:00 PM',
    },
]

export const OptionsUserLevel = [
    { label: 'ADMIN USER', value: 'admin' },
    { label: 'SUPER USER', value: 'super' },
    { label: 'REGULAR USER', value: 'regular' },
]

export const ModuleAdjustments = [
    { label: 'Dashboard', value: false },
    { label: 'Quotation', value: false },
    { label: 'Forwarding', value: false },
    { label: 'Liner Agency', value: false },
    { label: 'Customs', value: false },
    { label: 'Wirehouse', value: false },
    { label: 'Port Transport', value: false },
    { label: 'Accounts', value: false },
    { label: 'User', value: true },
]

export const OptionsClient = [
    { label: 'ONEBYONEAUS', value: 'onebyone_aus' },
    { label: 'ONEBYONEIND', value: 'onebyone_ind' },
    { label: 'ONEBYONESG', value: 'onebyone_sg' },
]

export const OptionsSite = [
    { label: 'SITE A', value: 'site_a' },
    { label: 'SITE B', value: 'site_b' },
    { label: 'SITE C', value: 'site_c' },
]

export const metaDummy: IMeta = {
    current_page: 1,
    last_page: 2,
    from: 1,
    to: 50,
    total_Items: 100,
    per_page: 0,
    total_page: 0,
    index_end: 0,
    index_start: 0,
}
